apiVersion: v1
data:
  DATABASE_URL: postgres://postgres:example@service-core-db:5432/service_core
  DEFAULT_FROM: default@fromemail.cm
  DISPATCHER_DATABASE_URL: postgres://postgres:example@service-core-db:5432/service_core
  DISPATCHER_DB_CHANNEL: dispatch_notifications_channel
  DISPATCHER_EXEC: ./scripts/send_mail.js
  DISPATCHER_MODE: both
  DISPATCHER_REDIS_URL: redis://dispatcher_redis:6379
  DISPATCHER_WORKERS: "2"
  SENDGRID_API_KEY: API_HERE
  SENTRY_DSN: SENTRY_DSN_CONNECTION_URL
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: notification-dispatcher-env
  name: notification-dispatcher-env
