FROM comum/deps:latest
RUN echo "ipv6" >> /etc/modules
WORKDIR /usr/app
COPY . .

RUN mkdir -p ./specs/logs
RUN cp -rf ./specs/postgrest/settings.config.sample ./specs/postgrest/settings.config
RUN wget https://github.com/begriffs/postgrest/releases/download/v0.4.3.0/postgrest-v0.4.3.0-ubuntu.tar.xz -O ./specs/postgrest/postgrest-0.4.3.0-linux.tar.xz
RUN cd ./specs/postgrest && tar -xvf postgrest-0.4.3.0-linux.tar.xz
RUN cd ./specs/postgrest && mv postgrest postgrest-0.4.3.0-linux
