version: 2
jobs:
  build:
    docker:
      - image: comum/docker-build-env:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce
      - run: ./test.sh

  deploy_production:
    docker:
      - image: comum/docker-build-env:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce
      - run: apk update && apk add git nodejs nodejs-npm bash
      - run: npm install heroku
      - run: bash .circleci/setup-heroku.sh
      - run: sh .circleci/deploy-heroku.sh

  deploy_sandbox:
    docker:
      - image: comum/docker-build-env:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce
      - run: apk update && apk add git nodejs nodejs-npm bash
      - run: npm install heroku
      - run: bash .circleci/setup-heroku.sh
      - run: sh .circleci/deploy-sandbox.sh

workflows:
  version: 2
  build-and-push:
    jobs:
      - build
      - deploy_sandbox:
          requires:
            - build
          filters:
            branches:
              only: develop
      - deploy_production:
          requires:
            - build
          filters:
            branches:
              only: master


