version: 2
jobs:
  build:
    docker:
      - image: comum/docker-build-env:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce
      # build the application container
      - run: docker build -t comum/notification-service:latest .
#
#  push_image:
#    docker:
#      - image: comum/docker-build-env:latest
#    steps:
#      - checkout
#      - setup_remote_docker:
#          version: 17.05.0-ce
#      # with credentials stored in the UI
#      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
#      # build the application container
#      - run: docker build -t comum/notification-service:latest .
#      # deploy the container
#      - run: docker push comum/notification-service:latest

  deploy_production:
    docker:
      - image: comum/docker-build-env:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce
      - run: apk update && apk add nodejs nodejs-npm bash
      - run: npm install heroku-cli
      - run: bash .circleci/setup-heroku.sh
      - run: sh .circleci/deploy-heroku.sh


  deploy_sandbox:
    docker:
      - image: comum/docker-build-env:latest
    steps:
      - checkout
      - add_ssh_keys
      - setup_remote_docker:
          version: 17.05.0-ce
      - run: apk update && apk add nodejs nodejs-npm bash
      - run: npm install heroku-cli
      - run: docker build -t comum/notification-service:latest .
      - run: sh .circleci/deploy-sandbox.sh


workflows:
  version: 2
  build-and-push:
    jobs:
      - build
      - push_image:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy_sandbox:
          requires:
            - build
          filters:
            branches:
              only: develop
      - deploy_production:
          requires:
            - build
          filters:
            branches:
              only: master
