# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


# for openapi gen
required = ["k8s.io/kube-openapi/cmd/openapi-gen"]

# general deps
[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

# kubernetes deps
[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.14"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.14"

[[constraint]]
  name = "k8s.io/apiserver"
  branch = "release-1.14"

# explicitely override gengo version, as the one picked by dep still uses glog,
# causing https://github.com/kubernetes/kubernetes/issues/74560
[[override]]
  name = "k8s.io/gengo"
  revision = "e17681d19d3ac4837a019ece36c2a0ec31ffe985"

# we need to pin to the same version as the one used by kube:
# https://github.com/kubernetes/apiserver/blob/8b27c41bdbb11ff103caa673315e097bf0289171/Godeps/Godeps.json#L453-L464
# otherwise the build fails
[[override]]
  name = "github.com/googleapis/gnostic"
  revision = "0c5108395e2debce0d731cf0287ddf7242066aba"

# we need to pin to the same version as the one used by kube:
# https://github.com/kubernetes/apiserver/blob/8b27c41bdbb11ff103caa673315e097bf0289171/Godeps/Godeps.json#L2093-L2112
[[override]]
  name = "sigs.k8s.io/structured-merge-diff"
  revision = "e85c7b244fd2cc57bb829d73a061f93a441e63ce"

# we need to pin to the same version as the one used by kube:
# https://github.com/kubernetes/apiserver/blob/8b27c41bdbb11ff103caa673315e097bf0289171/Godeps/Godeps.json#L373-L376
[[override]]
  name = "github.com/evanphx/json-patch"
  revision = "5858425f75500d40c52783dce87d085a483ce135"

# see Godeps.json from k8s.io/apiserver@release-1.14:
# https://github.com/kubernetes/apiserver/blob/8b27c41bdbb11ff103caa673315e097bf0289171/Godeps/Godeps.json#L2049-L2076
[[constraint]]
  name = "k8s.io/kube-openapi"
  revision = "b3a7cee44a305be0a69e1b9ac03018307287e1b0"

[[constraint]]
  name = "k8s.io/client-go"
  branch = "release-11.0"

[[constraint]]
  name = "k8s.io/kubernetes"
  branch = "release-1.14"

[[constraint]]
  name = "k8s.io/metrics"
  branch = "release-1.14"

# test deps
[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.5.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.4.0"

[prune]
  go-tests = true
  unused-packages = true
