#!/bin/sh

export PORT=80
export PROTO_SCHEMA=http
export PAYMENT_SERVICE_API_SERVER=127.0.0.1:3000
export PROJECT_SERVICE_API_SERVER=127.0.0.1:3000
export COMMUNITY_SERVICE_API_SERVER=127.0.0.1:3000
export ANALYTICS_SERVICE_API_SERVER=127.0.0.1:3000
export NOTIFICATION_SERVICE_API_SERVER=127.0.0.1:3000
export CATARSE_MOMENT_SERVICE_API_SERVER=127.0.0.1:3000
export RECOMMENDER_SERVICE_API_SERVER=127.0.0.1:3000
export COMMON_SERVICE_API_SERVER=127.0.0.1:3000
export DNS_RESOLVER=127.0.0.1

echo 'preparing envstub for test'
envsubst '$$PORT $$PROTO_SCHEMA $$PAYMENT_SERVICE_API_SERVER $$PROJECT_SERVICE_API_SERVER $$COMMUNITY_SERVICE_API_SERVER $$ANALYTICS_SERVICE_API_SERVER $$NOTIFICATION_SERVICE_API_SERVER $$CATARSE_MOMENT_SERVICE_API_SERVER $$RECOMMENDER_SERVICE_API_SERVER $$COMMON_SERVICE_API_SERVER $$DNS_RESOLVER' < /etc/nginx/conf.d/proxy.template > /etc/nginx/conf.d/default.conf
echo 'done env stub'

echo 'running nginx -t'
nginx -t

echo 'removing test syntax file'
