apiVersion: batch/v1
kind: Job
metadata:
  name: fdw-settings
spec:
  template:
    spec:
      containers:
        - name: fdw-settings
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: CATARSE_DB_URI
                  name: catarse-secrets
            - name: RAILS_ENV
              value: development
            - name: REDIS_URL
              value: redis://catarse-redis:6379
          image: 892910702142.dkr.ecr.us-east-1.amazonaws.com/catarse-deploy/catarse
          command:
            - bundle
            - exec
            - rake
            - common:generate_fdw
      restartPolicy: OnFailure

