// flow-typed signature: bda6762ea03d15b7c61ca6b7901abcd3
// flow-typed version: <<STUB>>/chartjs_v^0.3.23/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chartjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'chartjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chartjs/chart' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chartjs/chart.js' {
  declare module.exports: $Exports<'chartjs/chart'>;
}
