// flow-typed signature: 76b9bf88bfc5c1e20359ab518fda7def
// flow-typed version: <<STUB>>/diacritics_v^1.2.3/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'diacritics'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'diacritics' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'diacritics/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'diacritics/index' {
  declare module.exports: $Exports<'diacritics'>;
}
declare module 'diacritics/index.js' {
  declare module.exports: $Exports<'diacritics'>;
}
declare module 'diacritics/test/test.js' {
  declare module.exports: $Exports<'diacritics/test/test'>;
}
