// flow-typed signature: 155c4180e59d8f8c4e0c5868ad2f7b08
// flow-typed version: <<STUB>>/i18n-js_v^1.0.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'i18n-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'i18n-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'i18n-js/i18n' {
  declare module.exports: any;
}

declare module 'i18n-js/spec/currency.spec' {
  declare module.exports: any;
}

declare module 'i18n-js/spec/current_locale.spec' {
  declare module.exports: any;
}

declare module 'i18n-js/spec/dates.spec' {
  declare module.exports: any;
}

declare module 'i18n-js/spec/defaults.spec' {
  declare module.exports: any;
}

declare module 'i18n-js/spec/interpolation.spec' {
  declare module.exports: any;
}

declare module 'i18n-js/spec/localization.spec' {
  declare module.exports: any;
}

declare module 'i18n-js/spec/numbers.spec' {
  declare module.exports: any;
}

declare module 'i18n-js/spec/placeholder.spec' {
  declare module.exports: any;
}

declare module 'i18n-js/spec/pluralization.spec' {
  declare module.exports: any;
}

declare module 'i18n-js/spec/prepare_options.spec' {
  declare module.exports: any;
}

declare module 'i18n-js/spec/translate.spec' {
  declare module.exports: any;
}

declare module 'i18n-js/spec/translations' {
  declare module.exports: any;
}

// Filename aliases
declare module 'i18n-js/i18n.js' {
  declare module.exports: $Exports<'i18n-js/i18n'>;
}
declare module 'i18n-js/spec/currency.spec.js' {
  declare module.exports: $Exports<'i18n-js/spec/currency.spec'>;
}
declare module 'i18n-js/spec/current_locale.spec.js' {
  declare module.exports: $Exports<'i18n-js/spec/current_locale.spec'>;
}
declare module 'i18n-js/spec/dates.spec.js' {
  declare module.exports: $Exports<'i18n-js/spec/dates.spec'>;
}
declare module 'i18n-js/spec/defaults.spec.js' {
  declare module.exports: $Exports<'i18n-js/spec/defaults.spec'>;
}
declare module 'i18n-js/spec/interpolation.spec.js' {
  declare module.exports: $Exports<'i18n-js/spec/interpolation.spec'>;
}
declare module 'i18n-js/spec/localization.spec.js' {
  declare module.exports: $Exports<'i18n-js/spec/localization.spec'>;
}
declare module 'i18n-js/spec/numbers.spec.js' {
  declare module.exports: $Exports<'i18n-js/spec/numbers.spec'>;
}
declare module 'i18n-js/spec/placeholder.spec.js' {
  declare module.exports: $Exports<'i18n-js/spec/placeholder.spec'>;
}
declare module 'i18n-js/spec/pluralization.spec.js' {
  declare module.exports: $Exports<'i18n-js/spec/pluralization.spec'>;
}
declare module 'i18n-js/spec/prepare_options.spec.js' {
  declare module.exports: $Exports<'i18n-js/spec/prepare_options.spec'>;
}
declare module 'i18n-js/spec/translate.spec.js' {
  declare module.exports: $Exports<'i18n-js/spec/translate.spec'>;
}
declare module 'i18n-js/spec/translations.js' {
  declare module.exports: $Exports<'i18n-js/spec/translations'>;
}
