// flow-typed signature: c8ffa670b5375cc95fb013671111e26e
// flow-typed version: <<STUB>>/mithril_v^0.2.4/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mithril'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'mithril' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mithril/mithril' {
  declare module.exports: any;
}

declare module 'mithril/mithril.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mithril/mithril.js' {
  declare module.exports: $Exports<'mithril/mithril'>;
}
declare module 'mithril/mithril.min.js' {
  declare module.exports: $Exports<'mithril/mithril.min'>;
}
