rvm:
  - 2.2.3

before_install:
  - "gem install bundler"

before_script:
  - "cp config/database.sample.yml config/database.yml"
  - "psql -c 'create role catarse SUPERUSER LOGIN;' postgres"
  - "psql -c 'create database catarse_test;' -U catarse postgres"
  - "sh -e /etc/init.d/xvfb start"
  - "bundle exec rails db:migrate"

env:
  - DISPLAY=:99.0

script:
  - "bundle exec rspec spec"

branches:
  only:
    - master
    - bootstrap
