# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.1'

gem 'auto_html', '2.1.1'
gem 'bootsnap', '1.11.1', require: false
gem 'browser', '5.3.1'
gem 'carrierwave', '2.2.2'
gem 'catarse_pagarme', path: 'engines/catarse_pagarme'
gem 'catarse_scripts', path: 'engines/catarse_scripts'
gem 'catarse_settings_db', path: 'engines/catarse_settings_db'
gem 'concurrent-ruby', '1.1.10'
gem 'countries', '5.0.0'
gem 'cpf_cnpj', '0.5.0'
gem 'cssbundling-rails', '1.1.0'
gem 'dbhero', github: 'catarse/dbhero', branch: 'master'
gem 'devise', '4.8.1'
gem 'draper', '4.0.2'
gem 'excelinator', github: 'stephannv/excelinator', branch: 'master'
gem 'faraday', '1.8.0' # ADDED TO BE COMPATIBLE WITH DBHERO; DON'T UPDATE
gem 'feedjira', '3.2.1'
gem 'gridhook', github: 'catarse/gridhook', branch: 'master'
gem 'has_scope', '0.8.0'
gem 'high_voltage', '3.1.2'
gem 'i18n_alchemy', '0.5.0'
gem 'i18n-js', '3.9.2'
gem 'inherited_resources', '1.13.1'
gem 'jsbundling-rails', '1.0.2'
gem 'jwt', '2.3.0'
gem 'kaminari', '1.2.2'
gem 'koala', '3.1.0'
gem 'mini_magick', '4.11.0'
gem 'money-rails', '1.15.0'
gem 'omniauth', '2.0.4'
gem 'omniauth-facebook', '9.0.0'
gem 'omniauth-google-oauth2', '1.0.1'
gem 'omniauth-rails_csrf_protection', '1.0.1'
gem 'parallel', '1.22.1'
gem 'pg', '1.3.5'
gem 'pg_search', '2.3.6'
gem 'postgres-copy', '1.6.0'
gem 'propshaft', '0.6.4'
gem 'puma', '5.6.4'
gem 'pundit', '2.2.0'
gem 'rack-cors', '1.1.1'
gem 'rails', '7.0.2.3'
gem 'rails-html-sanitizer', '1.4.2'
gem 'rails-observers', '0.1.5'
gem 'ranked-model', '0.4.8'
gem 'rdstation-ruby-client', '0.0.5' # DONT UPDATE
gem 'redactor-rails', '0.7.0', github: 'catarse/redactor-rails', branch: 'master'
gem 'redis', '4.6.0'
gem 'responders', '3.0.1'
gem 'rqrcode', '2.1.1'
gem 'sendgrid-ruby', '4.0.6' # DON'T UPDATE
gem 'sentry-rails', '5.2.1'
gem 'sidekiq', '6.4.1'
gem 'sidekiq-status', '2.1.3'
gem 'simple_form', '5.1.0'
gem 'simple_token_authentication', github: 'stephannv/simple_token_authentication', branch: 'master'
gem 'sitemap_generator', '6.2.1'
gem 'slim-rails', '3.4.0'
gem 'state_machines-activerecord', '0.8.0'
gem 'statesman', '9.0.1'
gem 'typhoeus', '1.4.0'
gem 'tzinfo-data', '1.2.7', platforms: %i[mingw mswin x64_mingw jruby]
gem 'user_notifier', '0.4.0', github: 'stephannv/user_notifier', branch: 'master'
gem 'video_info', '3.0.2'
gem 'whenever', '1.0.0'
gem 'zendesk_api', '1.35.0'

group :production do
  gem 'fog-aws', '3.13.0'
end

group :development do
  gem 'brakeman', '5.2.1'
  gem 'letter_opener', '1.8.1'
  gem 'listen', '3.7.1'
  gem 'rack-mini-profiler', '3.0.0'
  gem 'web-console', '4.2.0'
end

group :development, :test do
  gem 'awesome_print', '1.9.2'
  gem 'debug', '1.5.0', platforms: %i[mri mingw x64_mingw]
  gem 'factory_bot_rails', '6.2.0'
  gem 'faker', '2.20.0'
end

group :test do
  gem 'rails-controller-testing', '1.0.5'
  gem 'rspec-rails', '5.1.1'
  gem 'shoulda-matchers', '5.1.0'
  gem 'webmock', '3.14.0'
end

group :code_analysis do
  gem 'rubocop', '1.26.1'
  gem 'rubocop-performance', '1.13.3'
  gem 'rubocop-rails', '2.14.2'
  gem 'rubocop-rspec', '2.9.0'
end
