apiVersion: v1
kind: Pod
metadata:
  labels:
    io.kompose.service: catarse-specs
  name: catarse-specs
spec:
  containers:
  - args:
    - bash
    - run_specs
    env:
    - name: DATABASE_URL
      value: postgres://catarse:example@localhostcatarse:5432/catarse_db_test
    - name: RAILS_ENV
      value: test
    - name: REDIS_URL
      value: redis://catarse_redis:6379
    image: catarse-specs
    name: catarse-specs
    resources: {}
  restartPolicy: Never
status: {}
