apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: analytics-service-api
  name: analytics-service-api
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      io.kompose.service: analytics-service-api
  template:
    metadata:
      labels:
        io.kompose.service: analytics-service-api
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: SERVICE_CORE_DB_URI
                  name: catarse-secrets
            - name: PGRST_DB_ANON_ROLE
              valueFrom:
                configMapKeyRef:
                  key: PGRST_DB_ANON_ROLE
                  name: analytics-service-api-compose-env
            - name: PGRST_DB_POOL
              valueFrom:
                configMapKeyRef:
                  key: PGRST_DB_POOL
                  name: analytics-service-api-compose-env
            - name: PGRST_DB_SCHEMA
              valueFrom:
                configMapKeyRef:
                  key: PGRST_DB_SCHEMA
                  name: analytics-service-api-compose-env
            - name: PGRST_DB_URI
              valueFrom:
                secretKeyRef:
                  key: JWT_SECRET
                  name: catarse-secrets
            - name: PGRST_SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  key: PGRST_SERVER_HOST
                  name: analytics-service-api-compose-env
            - name: PGRST_SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  key: PGRST_SERVER_PORT
                  name: analytics-service-api-compose-env
            - name: PGRST_SERVER_PROXY_URI
              valueFrom:
                configMapKeyRef:
                  key: PGRST_SERVER_PROXY_URI
                  name: analytics-service-api-compose-env
            - name: POSTGREST_VER
              valueFrom:
                configMapKeyRef:
                  key: POSTGREST_VER
                  name: analytics-service-api-compose-env
            - name: PROCESS_PAYMENT_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: SERVICE_CORE_DB_URI
                  name: catarse-secrets
          image: postgrest/postgrest:v0.4.4.0
          name: analytics-service-api
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: analytics-service-api
  name: analytics-service-api
spec:
  ports:
  - name: "3005"
    port: 3005
    targetPort: 3000
  selector:
    io.kompose.service: analytics-service-api
status:
  loadBalancer: {}
  