apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: catarse-moment-service-api
  name: catarse-moment-service-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: catarse-moment-service-api
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: catarse-moment-service-api
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: CATARSE_MOMENTS_DB_URI
                  name: catarse-secrets
            - name: PGRST_DB_ANON_ROLE
              valueFrom:
                configMapKeyRef:
                  key: PGRST_DB_ANON_ROLE
                  name: catarse-moment-service-api-env
            - name: PGRST_DB_POOL
              valueFrom:
                configMapKeyRef:
                  key: PGRST_DB_POOL
                  name: catarse-moment-service-api-env
            - name: PGRST_DB_SCHEMA
              valueFrom:
                configMapKeyRef:
                  key: PGRST_DB_SCHEMA
                  name: catarse-moment-service-api-env
            - name: PGRST_DB_URI
              valueFrom:
                secretKeyRef:
                  key: CATARSE_MOMENTS_DB_URI
                  name: catarse-secrets
            - name: PGRST_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: JWT_SECRET
                  name: catarse-secrets
            - name: PGRST_SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  key: PGRST_SERVER_HOST
                  name: catarse-moment-service-api-env
            - name: PGRST_SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  key: PGRST_SERVER_PORT
                  name: catarse-moment-service-api-env
            - name: PGRST_SERVER_PROXY_URI
              valueFrom:
                configMapKeyRef:
                  key: PGRST_SERVER_PROXY_URI
                  name: catarse-moment-service-api-env
            - name: POSTGREST_VER
              valueFrom:
                configMapKeyRef:
                  key: POSTGREST_VER
                  name: catarse-moment-service-api-env
          image: postgrest/postgrest:v0.4.4.0
          name: catarse-moment-service-api
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: catarse-moment-service-api
  name: catarse-moment-service-api
spec:
  ports:
  - name: "3010"
    port: 3010
    targetPort: 3000
  selector:
    io.kompose.service: catarse-moment-service-api
status:
  loadBalancer: {}
  