apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k83/
    kompose.version: 1.19.0 (f63a961c)
  
  labels:
    io.kompose.service: hook-service-api
  name: hook-service-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: hook-service-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k83/
        kompose.version: 1.19.0 (f63a961c)
      labels:
        io.kompose.service: hook-service-api
    spec:
      containers:
        - args:
            - npm
            - start
            - server.js
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: SERVICE_CORE_DB_URI
                  name: catarse-secrets
            - name: GATEWAY_API_KEY
              valueFrom:
                secretKeyRef:
                  key: GATEWAY_API_KEY
                  name: catarse-secrets
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  key: SENTRY_DSN
                  name: catarse-secrets
          image: catarse-deploy/hook-service-api
          name: hook-service-api
          ports:
            - containerPort: 4444
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o k83/
    kompose.version: 1.19.0 (f63a961c)
  
  labels:
    io.kompose.service: hook-service-api
  name: hook-service-api
spec:
  ports:
  - name: "3006"
    port: 3006
    targetPort: 4444
  selector:
    io.kompose.service: hook-service-api
status:
  loadBalancer: {}
