apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k83/
    kompose.version: 1.19.0 (f63a961c)
  
  labels:
    io.kompose.service: notification-dispatcher
  name: notification-dispatcher
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: notification-dispatcher
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k83/
        kompose.version: 1.19.0 (f63a961c)
      labels:
        io.kompose.service: notification-dispatcher
    spec:
      containers:
        - args:
            - ./dispatchers/notification_dispatcher
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: SERVICE_CORE_DB_URI
                  name: catarse-secrets
            - name: DEFAULT_FROM
              valueFrom:
                configMapKeyRef:
                  key: DEFAULT_FROM
                  name: notification-dispatcher-env
            - name: DISPATCHER_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: SERVICE_CORE_DB_URI
                  name: catarse-secrets
            - name: DISPATCHER_DB_CHANNEL
              valueFrom:
                configMapKeyRef:
                  key: DISPATCHER_DB_CHANNEL
                  name: notification-dispatcher-env
            - name: DISPATCHER_EXEC
              valueFrom:
                configMapKeyRef:
                  key: DISPATCHER_EXEC
                  name: notification-dispatcher-env
            - name: DISPATCHER_MODE
              valueFrom:
                configMapKeyRef:
                  key: DISPATCHER_MODE
                  name: notification-dispatcher-env
            - name: DISPATCHER_REDIS_URL
              valueFrom:
                configMapKeyRef:
                  key: DISPATCHER_REDIS_URL
                  name: notification-dispatcher-env
            - name: DISPATCHER_WORKERS
              valueFrom:
                configMapKeyRef:
                  key: DISPATCHER_WORKERS
                  name: notification-dispatcher-env
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  key: SENDGRID_API_KEY
                  name: catarse-secrets
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  key: SENTRY_DSN
                  name: catarse-secrets
          image: catarse-deploy/notification-dispatcher
          name: notification-dispatcher
          resources: {}
      restartPolicy: Always
status: {}
