apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k83/
    kompose.version: 1.19.0 (f63a961c)
  
  labels:
    io.kompose.service: payment-service-api
  name: payment-service-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: payment-service-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k83/
        kompose.version: 1.19.0 (f63a961c)
      labels:
        io.kompose.service: payment-service-api
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: SERVICE_CORE_DB_URI
                  name: catarse-secrets
            - name: PGRST_DB_ANON_ROLE
              valueFrom:
                configMapKeyRef:
                  key: PGRST_DB_ANON_ROLE
                  name: payment-service-api-env
            - name: PGRST_DB_POOL
              valueFrom:
                configMapKeyRef:
                  key: PGRST_DB_POOL
                  name: payment-service-api-env
            - name: PGRST_DB_SCHEMA
              valueFrom:
                configMapKeyRef:
                  key: PGRST_DB_SCHEMA
                  name: payment-service-api-env
            - name: PGRST_DB_URI
              valueFrom:
                secretKeyRef:
                  key: SERVICE_CORE_DB_URI
                  name: catarse-secrets
            - name: PGRST_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: JWT_SECRET
                  name: catarse-secrets
            - name: PGRST_SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  key: PGRST_SERVER_HOST
                  name: payment-service-api-env
            - name: PGRST_SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  key: PGRST_SERVER_PORT
                  name: payment-service-api-env
            - name: PGRST_SERVER_PROXY_URI
              valueFrom:
                configMapKeyRef:
                  key: PGRST_SERVER_PROXY_URI
                  name: payment-service-api-env
            - name: POSTGREST_VER
              valueFrom:
                configMapKeyRef:
                  key: POSTGREST_VER
                  name: payment-service-api-env
            - name: PROCESS_PAYMENT_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: SERVICE_CORE_DB_URI
                  name: catarse-secrets
          image: postgrest/postgrest:v0.4.4.0
          name: payment-service-api
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o k83/
    kompose.version: 1.19.0 (f63a961c)
  
  labels:
    io.kompose.service: payment-service-api
  name: payment-service-api
spec:
  ports:
  - name: "3001"
    port: 3001
    targetPort: 3000
  selector:
    io.kompose.service: payment-service-api
status:
  loadBalancer: {}
