apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k83/
    kompose.version: 1.19.0 (f63a961c)
  
  labels:
    io.kompose.service: payment-stream-processor
  name: payment-stream-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: payment-stream-processor
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k83/
        kompose.version: 1.19.0 (f63a961c)
      labels:
        io.kompose.service: payment-stream-processor
    spec:
      containers:
        - args:
            - ./dispatchers/payment_stream_processor
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: SERVICE_CORE_DB_URI
                  name: catarse-secrets
            - name: DISPATCHER_CHANNEL
              valueFrom:
                configMapKeyRef:
                  key: DISPATCHER_CHANNEL
                  name: payment-stream-processor-env
            - name: DISPATCHER_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: SERVICE_CORE_DB_URI
                  name: catarse-secrets
            - name: DISPATCHER_EXEC
              valueFrom:
                configMapKeyRef:
                  key: DISPATCHER_EXEC
                  name: payment-stream-processor-env
            - name: DISPATCHER_MODE
              valueFrom:
                configMapKeyRef:
                  key: DISPATCHER_MODE
                  name: payment-stream-processor-env
            - name: DISPATCHER_REDIS_URL
              valueFrom:
                configMapKeyRef:
                  key: DISPATCHER_REDIS_URL
                  name: payment-stream-processor-env
            - name: DISPATCHER_WORKERS
              valueFrom:
                configMapKeyRef:
                  key: DISPATCHER_WORKERS
                  name: payment-stream-processor-env
            - name: GATEWAY_API_KEY
              valueFrom:
                secretKeyRef:
                  key: GATEWAY_API_KEY
                  name: catarse-secrets
            - name: POSTBACK_URL
              valueFrom:
                configMapKeyRef:
                  key: POSTBACK_URL
                  name: payment-stream-processor-env
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  key: SENTRY_DSN
                  name: catarse-secrets
          image: catarse-deploy/payments
          name: payment-stream-processor
          resources: {}
      restartPolicy: Always
status: {}
