apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k83/
    kompose.version: 1.19.0 (f63a961c)
  
  labels:
    io.kompose.service: recommender-service-api
  name: recommender-service-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: recommender-service-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k83/
        kompose.version: 1.19.0 (f63a961c)
      labels:
        io.kompose.service: recommender-service-api
    spec:
      containers:
        - args:
            - gunicorn
            - -w
            - '4'
            - -b
            - 0.0.0.0:3009
            - catarse_recommender.application:app
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_URL
                  name: recommender-service-api-env
            - name: FLASK_APP
              valueFrom:
                configMapKeyRef:
                  key: FLASK_APP
                  name: recommender-service-api-env
            - name: LANG
              valueFrom:
                configMapKeyRef:
                  key: LANG
                  name: recommender-service-api-env
            - name: LC_ALL
              valueFrom:
                configMapKeyRef:
                  key: LC_ALL
                  name: recommender-service-api-env
            - name: PYTHONPATH
              valueFrom:
                configMapKeyRef:
                  key: PYTHONPATH
                  name: recommender-service-api-env
          image: catarse-deploy/recommender-service-api
          name: recommender-service-api
          ports:
            - containerPort: 3009
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o k83/
    kompose.version: 1.19.0 (f63a961c)
  
  labels:
    io.kompose.service: recommender-service-api
  name: recommender-service-api
spec:
  ports:
  - name: "3009"
    port: 3009
    targetPort: 3009
  selector:
    io.kompose.service: recommender-service-api
status:
  loadBalancer: {}
