apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k83/
    kompose.version: 1.19.0 (f63a961c)
  
  labels:
    io.kompose.service: catarse-db
  name: catarse-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: catarse-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k83/
        kompose.version: 1.19.0 (f63a961c)
      labels:
        io.kompose.service: catarse-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: catarse_db
            - name: POSTGRES_USER
              value: catarse
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: catarse-secrets
            - name: PGDATA
              value: /ebs/data
          volumeMounts:
            - mountPath: /ebs
              name: catarse-data
          image: 892910702142.dkr.ecr.us-east-1.amazonaws.com/catarse-deploy/catarse-db
          name: catarse-db
          ports:
            - containerPort: 5432
          resources: {}
      restartPolicy: Always
      volumes:
        - name: catarse-data
          persistentVolumeClaim:
            claimName: catarse-data
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: catarse-db
  name: catarse-db
spec:
  ports:
  - port: 5432
  selector:
    io.kompose.service: catarse-db
status:
  loadBalancer: {}
  